name: child_abuse_prevention
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  google_fonts: ^4.0.4
  pin_code_fields: ^7.4.0
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  image_picker: ^0.8.8
  group_radio_button: ^1.3.0
  flutter_overlay_window: ^0.4.3
  system_alert_window: ^1.2.1
  get: ^4.6.5
  geolocator: ^9.0.2
  http: ^0.13.5
  shake: ^2.0.0
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  flutter_html: ^3.0.0-alpha.6
  expandable: ^5.0.1
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # macos_ui:
  #   git:
  #     url: https://github.com/Mayb3Nots/macos_ui.git
  #     ref: dev
  modal_bottom_sheet: 
    git: 
      url: https://github.com/danReynolds/modal_bottom_sheet.git 
      path: modal_bottom_sheet

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
